### ISSUE TITLE
Support Ajax

### ISSUE THREAD

**Issue by Mister-42** [yiisoft/view#126]
Now that I have your attention, **please do not support Ajax**. A lot of time will go into that, which can be spend much better. That being said, I do miss one specific option to support my Ajax implementation that I cannot bypass completely.

I render my Ajax replies currently with renderPartial, which has the slight drawback that registered javascript (`$this->registerJs`, `$this->jsStrings`, `$this->jsVars`) will not be included in the response. My request is to add a way to basically do renderPartialWithJavascript.

**Comment by samdark** [comment]
How about using `render()` with empty layout instead?

**Comment by Mister-42** [comment]
You, kind sir, win the internet today.

If people need a solution in the future, here is the minimal layout you'll need:
```php
<?php

declare(strict_types=1);

$this->beginPage();
$this->beginBody();
echo $content;
$this->endBody();
$this->endPage();
```
