### ISSUE TITLE
Use LoggerAwareInterface

### ISSUE THREAD

**Issue by roxblnfk** [yiisoft/view#133]
https://github.com/yiisoft/view/blob/33fceb7dc7ed93d4d472ff6beb9ab8f65cd7c9f8/src/View.php#L117

 I think it better to remove LoggerInterface from the constructor and implement [LoggerAwareInterface](https://github.com/php-fig/log/blob/master/Psr/Log/LoggerAwareInterface.php) instead.

**Comment by samdark** [comment]
Thought about it. Decided to leave it as is.

**Comment by roxblnfk** [comment]
Related: https://github.com/yiisoft/view/issues/161
