### ISSUE TITLE
Concept: finalize View and WebView class

### ISSUE THREAD

**Issue by vjik** [yiisoft/view#140]
**Variant 1**

1) Create trait `ViewTrait` with content from `View` class and mark him as `@internal`.
2) `View` class only `use ViewTrait` and finalized.
3) `WebView` class not extends `View` but `use ViewTrait` and finalized.

**Variant 2**

1) Create class `BaseView` with content from `View` class and mark him as `@internal`.
2) `View` extends `BaseView` and finalized.
3) `WebView` extends `BaseView` and finalized.

----

I like variant 2.

**Comment by samdark** [comment]
What do you want to achieve with the change?

**Comment by vjik** [comment]
> What do you want to achieve with the change? What problem do you want to fix?

Finalize classes. `View` and `WebView` must not be inherited outside package.

**Comment by samdark** [comment]
abstract BaseView would do.
