### ISSUE TITLE
Add default value to BaseView::getCommonParameter()

### ISSUE THREAD

**Issue by vjik** [yiisoft/view#177]
For example:

```php
// throws InvalidArgumentException
$view->getCommonParameter('non-exists-parameter');

// return 42
$view->getCommonParameter('non-exists-parameter', 42);
```

**Comment by terabytesoftw** [comment]
What would be the use case, for me it doesn't make sense to pass a value in a get?

**Comment by vjik** [comment]
> What would be the use case, for me it doesn't make sense to pass a value in a `get()`, it looks like a hack ?

Use case: https://github.com/yiisoft/yii-widgets/pull/36/files#diff-9af7cbc9482b96d8d6612ce55840fd1338c88716c03623d2c46ab514d3aac9d2R50

**Comment by samdark** [comment]
We can use `$view->getCommonParameter('non-exists-parameter') ?? 42` but it won't really do isset so it won't be possible to store `null` as parameter value. I think for such use-cases it's useful.
