### ISSUE TITLE
Add ability to render view from string

### ISSUE THREAD

**Issue by RomeroMsk** [yiisoft/view#19]
I can't find the way to render a view from string (not from file). I want to use template engine (Twig or Smarty) to render texts from templates stored in DB. For example, store email message template in DB table and generate email body from it on the fly.

**Comment by samdark** [comment]
https://github.com/yiisoft/yii2/pull/15116

**Comment by mikk150** [comment]
I have something that renders strings stored in SQL
https://github.com/mikk150/yii2-sql-renderer

adopt it a bit and do your magic

**Comment by samdark** [comment]
After thinking, I don't think we should explicitly support that because it will suggest doing that is alright, especially with `eval()`. https://github.com/yiisoft/view/issues/122 may be an option.
