### ISSUE TITLE
Use incorrect template with default extension

### ISSUE THREAD

**Issue by vjik** [yiisoft/view#227]
See test:
https://github.com/yiisoft/view/blob/master/tests/ViewTest.php#L182-L198

Code:

```php
$view->withDefaultExtension('txt')->render('file');
```

... must use `file.txt` and throw exception if not found. But not if not found then used `file.php`. Seems, it's incorrect behaviour.

**Comment by rustamwin** [comment]
Can we transform this behaviour to fallback extension?

**Comment by samdark** [comment]
It is expected behavior.
