### ISSUE TITLE
Proposal divides Asset and Widgets in separate packages

### ISSUE THREAD

**Issue by terabytesoftw** [yiisoft/view#34]
Hi, proposal divides Asset and Widgets in separate packages,

**Comment by samdark** [comment]
Could be done. What are your reasons for it?

**Comment by terabytesoftw** [comment]
I think that the package view must include all the files of the same, I do not need to have the widgets in it, the idea of separating the packages is to use what you need.

I understand that Assets and Widgets need yii libraries to work in that case I would propose to create yiisoft / yii-asset (Yiisoft/ Yii/Asset), and yiisoft/yii-widgets (Yiisoft/Yii/Widgets).

**Comment by samdark** [comment]
Assets are very tightly coupled with View. View registers assets while assets themselves are only "configs". To me separating these two does not sound good.

Widgets could be, indeed, extracted.

**Comment by terabytesoftw** [comment]
Already more or less I have the refactoring of widget.php, we could open a repository only for the base widget, so yii-bootstrap4 and any other widget will only depend on it and not the complete package, in addition, it should be a good idea to Open a package of standard widgets.

Since the widget parameters were previously made by the container, now create a setConfig class inside the widget.php that passes the parameters and so the widgets work smoothly.

**Comment by samdark** [comment]
Interesting. The widget does not work without View component, right?

**Comment by terabytesoftw** [comment]
I just tested the component by removing the implementation of ViewContextInterface, and it works fine I think we can decouple it and use it independently of the view, just to use navbar and nav of yii-bootstrap4, I think it would only be necessary to depend on the view to register the assets, of course we should review deeper.

**Comment by samdark** [comment]
How about render method of the widget?

**Comment by terabytesoftw** [comment]
Few widgets need to render a view, at least Yii-Bootstrap4, and the standard Yii Widgets I think they don't, I have reviewed and no widget maintained by the frame render a view, obviously Yii2 allows that functionality and it would be nice to keep it in Yii3, but I assure you that many of them can work independently of the view, I would say they are more helpers than widgets.

**Comment by samdark** [comment]
I see. So you suggest that individual widgets could require view package and implement `ViewContextInterface`? That would have make sense but:

1. `yiisoft/yii-web` already requires `view` and widgets are to be used with web app.
2. Implementing `ViewContextInterface` each time is cumbersome. I'd provide a base abstract class instead with implementation done.

**Comment by terabytesoftw** [comment]
It is possible to separate the Widgets from the view, I have already done it, the widgets that need the view are injected into the constructor, and the widget factory is injected into the view through setDeafaultParameters, everything works perfect, the widgets block and contentDecorator the code is added to the view since they are simple widgets.

ViewFactory:

```
class ViewFactory
{
    public function __invoke(ContainerInterface $container)
    {
        $aliases = $container->get(Aliases::class);
        $assetManager = $container->get(AssetManager::class);
        $assetManager->setBasePath($aliases->get('@basePath'));
        $assetManager->setBaseUrl($aliases->get('@baseUrl'));
        $assetConverter = $container->get(AssetConverter::class);
        $eventDispatcher = $container->get(EventDispatcherInterface::class);
        $logger = $container->get(LoggerInterface::class);
        $theme = $container->get(Theme::class);
        $view = $aliases->get('@views');
        $widget = $container->get(Widget::class);
        $webView = new WebView($view, $theme, $eventDispatcher, $logger);
        $webView->setAssetManager($assetManager);
        $webView->setDefaultParameters(['widget' => $widget]);
        $facades = $container->get(AbstractFacade::class);

        return $webView;
    }
}
```
```
class View.php: [Add widget block, contentDecorator]
    public function beginBlock(string $idBlock, bool $renderInPlace = false): void
    {
        $this->idBlock = $idBlock;
        $this->renderInPlace = $renderInPlace;

        ob_start();
        ob_implicit_flush(0);
    }

    public function endBlock(): void
    {
        $block = ob_get_clean();

        if ($this->renderInPlace) {
            echo $block;
        }

        if (!empty($block)) {
            $this->setBlocks($this->idBlock, $block);
        }
    }

    public function beginContent(string $viewContent, array $paramContent = []): void
    {
        $this->viewContent = $viewContent;
        $this->paramContent = $paramContent;

        ob_start();
        ob_implicit_flush(0);
    }

    public function endContent(): void
    {
        $params = $this->paramContent;
        $params['content'] = ob_get_clean();

        echo $this->renderFile($this->viewContent, $params);
    }
```

```
class Widget.php
    public function begin(string $class, array $constructorArguments = []): Widget
    {
        $widget = $this->create($class, $constructorArguments);

        $this->stack[] = $widget;

        return $widget;
    }

    public function create(string $class, array $constructorArguments = []): Widget
    {
        $constructorArguments= array_merge([$this->eventDispatcher], $constructorArguments);
        $widget = new ReflectionClass($class);
        $widget = $widget->newInstanceArgs($constructorArguments);

        return $widget;
    }

    public function end(string $class): Widget
    {
        if (!empty($this->stack)) {
            $widget = array_pop($this->stack);
            if (get_class($widget) === $class) {
                /* @var $widget Widget */
                if ($widget->beforeRun()) {
                    $result = $widget->run();
                    $result = $widget->afterRun($result);
                    echo $result;
                }
                return $widget;
            }
            throw new InvalidConfigException(
                'Expecting end() of ' . get_class($widget) . ', found ' . get_called_class()
            );
        }
        throw new InvalidConfigException(
            'Unexpected ' . get_called_class() . '::end() call. A matching begin() is not found.'
        );
    }
```

Usages in Views/Layouts:

<?php $widget->begin(NavBar::class, [$this])
    ->brandLabel($params['app.name'])
    ->brandUrl($params['app.home.url'])
    ->options([
        'class' => 'navbar navbar-dark bg-dark navbar-expand-lg text-white',
    ])
    ->init();

   echo $widget->create(Nav::class, [$this])
        ->activateParents(true)
        ->currentPath($currentPath)
        ->items($menuItems)
        ->options(['class' => 'navbar-nav float-right ml-auto']);

$widget->end(NavBar::class) ?>

**Comment by samdark** [comment]
That looks interesting. I like overall idea.

> <?php $widget->begin(NavBar::class, [$this])

Can't it be `$navBar = (new NavBar($this))->brandLabel()...`?

> $widget->end(NavBar::class) ?>

How about `$navBar->end()`?

**Comment by terabytesoftw** [comment]
This would be my proposal:

```
Widget.php

    public function __construct(WebView $webView)
    {
        $this->eventDispatcher = $webView->getEventDispatcher();
    }

    /**
     * Begin the rendering of content.
     *
     * @return Widget
     */
    public function begin(): Widget
    {
        $this->stack[] = $this;

        return $this;
    }

    /**
     * Ends the rendering of content.
     *
     * @param string $class
     *
     * @return Widget
     */
    public function end(): Widget
    {
        if (!empty($this->stack)) {
            $widget = array_pop($this->stack);

            if (get_class($widget) === get_called_class()) {
                /* @var $widget Widget */
                if ($widget->beforeRun()) {
                    $result = $widget->run();
                    $result = $widget->afterRun($result);
                    echo $result;
                }
                return $widget;
            }
            throw new InvalidConfigException(
                'Expecting end() of ' . get_class($widget) . ', found ' . get_called_class()
            );
        }
        throw new InvalidConfigException(
            'Unexpected ' . get_called_class() . '::end() call. A matching begin() is not found.'
        );
    }

    /**
     * Executes the widget.
     *
     * @return string the result of widget execution to be outputted.
     */
    public function run(): string
    {
        $out = '';

        if ($this->beforeRun()) {
            $result = $this->getContent();
            $out = $this->afterRun($result);
        }

        return $out;
    }
```

```
Example Widgets Begin/End:

$spaceless = new Spaceless($this->webView);

$spaceless->begin()->init();
    echo "\t<div class='wrapper'>\n";

    $spaceless->begin()->init();
        echo "\t\t<div class='left-column'>\n";
        echo "\t\t\t<p>This is a left bar!</p>\n";
        echo "\t\t</div>\n\n";
        echo "\t\t<div class='right-column'>\n";
        echo "\t\t\t<p>This is a right bar!</p>\n";
        echo "\t\t</div>\n";
    $spaceless->end();

    echo "\t</div>\n";
$spaceless->end();
```

```
Example Widget:

echo (new Menu($this->webView))
    ->linkTemplate('')
    ->labelTemplate('')
    ->items([
        [
            'label'    => 'item1',
            'url'      => '#',
            'template' => 'label: {label}; url: {url}',
            'active'   => function ($item, $hasActiveChild, $isItemActive, $widget) {
                return isset($item, $hasActiveChild, $isItemActive, $widget);
            },
        ],
        [
            'label'    => 'item2',
            'template' => 'label: {label}',
            'active'   => false,
        ],
        [
            'label'  => 'item3 (no template)',
            'active' => 'somestring',
        ],
    ]);
```
```
In case of adding more dependencies to the constructs it is simple:

    public function __construct(WebView $webView, LoggerInterface $logger)
    {
        parent::__construct($webView);
        $this->logger = $logger;
    }
```

I await the comments.

**Comment by samdark** [comment]
Widget example looks fine. Straightforward, simple, no magic. 

> $spaceless->begin()->init();

What is `init()` in Begin/End example?

**Comment by samdark** [comment]
Also I guess

>    $this->stack[] = $this;

Could fail for nested view partials.

**Comment by terabytesoftw** [comment]
> Widget example looks fine. Straightforward, simple, no magic.
> 
> > $spaceless->begin()->init();
> 
> What is `init()` in Begin/End example?

```
class Spaceless extends Widget
{
    /**
     * Starts capturing an output to be cleaned from whitespace characters between HTML tags.
     */
    public function init(): void
    {
        ob_start();
        ob_implicit_flush(0);
    }

    /**
     * Marks the end of content to be cleaned from whitespace characters between HTML tags.
     * Stops capturing an output and returns cleaned result.
     *
     * @return string the result of widget execution to be outputted.
     */
    public function run(): string
    {
        return trim(preg_replace('/>\s+</', '><', ob_get_clean()));
    }
}
```

hi, the begin / end widgets must execute two  methods init and run, within the begin method, the init method could be called, because the options were passed in array, now it is done through setters which makes it impossible to call the method directly.

**Comment by terabytesoftw** [comment]
> Also I guess
> 
> > $this->stack[] = $this;
> 
> Could fail for nested view partials.

You could provide an example to prove it.

**Comment by samdark** [comment]
@terabytesoftw why do we need `init()` to be separate from `begin()`?

**Comment by samdark** [comment]
> within the begin method, the init method could be called, because the options were passed in array, now it is done through setters which makes it impossible to call the method directly.

Can't we get rid of separate `init()` call merging it into `begin()`?

> You could provide an example to prove it.

Thought more about it. The idea was about header.php and footer.php where begin is in the header but end is in the footer but that's terrible idea to do it like that so failing in this case is actually a good choice.

**Comment by terabytesoftw** [comment]
> > within the begin method, the init method could be called, because the options were passed in array, now it is done through setters which makes it impossible to call the method directly.
> 
> Can't we get rid of separate `init()` call merging it into `begin()`?
> 
> > You could provide an example to prove it.
> 
> Thought more about it. The idea was about header.php and footer.php where begin is in the header but end is in the footer but that's terrible to do it like that so failing in this case is actually a good choice.



> > within the begin method, the init method could be called, because the options were passed in array, now it is done through setters which makes it impossible to call the method directly.
> 
> Can't we get rid of separate `init()` call merging it into `begin()`?
> 
> > You could provide an example to prove it.
> 
> Thought more about it. The idea was about header.php and footer.php where begin is in the header but end is in the footer but that's terrible to do it like that so failing in this case is actually a good choice.

We cannot merging begin() return Widget, init() return void, but this solution may work.

Widget.php
```
public function begin(): Widget
{
    $this->stack[] = $this;
    $this->init();
    return $this;
}
```
Example Widgets:
```
<?php $navBar = (new NavBar($this))
    ->brandLabel($params['app.name'])
    ->brandUrl($params['app.home.url'])
    ->options([
        'class' => 'navbar navbar-dark bg-dark navbar-expand-lg text-white',
    ])
    ->begin();

    echo (new Nav($this))
        ->activateParents(true)
        ->currentPath($currentPath)
        ->items($menuItems)
        ->options(['class' => 'navbar-nav float-right ml-auto']);

$navBar->end() ?>
```

**Comment by samdark** [comment]
Looks much better. No additional comments.

**Comment by samdark** [comment]
Now as yiisoft/widget is done need to clean up this repository:

1. Remove widget itself.
2. Move all widgets to https://github.com/yiisoft/yii-widgets
3. Adjust namespaces leaving View only, see #69
