### ISSUE TITLE
Eliminate the core framework from all default style of frontend (bootstrap 3) framework

### ISSUE THREAD

**Issue by adiramardiani** [yiisoft/view#36]
For 2.1 version, I think the core framework must clean from bootstrap style especially in default variable config, what I see :
* [Widget](https://github.com/yiisoft/yii2-framework/tree/2.1/widgets)
* [Grid](https://github.com/yiisoft/yii2-framework/tree/2.1/widgets)
* etc

Have a default bootstrap class style,
From beginner thinking, yii 2 is framework for bootsrap 3, because the html class or style is write for this framework by default not pure html, in yii 2.1 this framework must provide enlightenment to beginner that this framework can be used for all html pure/frameworks

For example, 
- [ActionColumn](https://github.com/yiisoft/yii2-framework/blob/2.1/grid/ActionColumn.php) : have default value icon a part of Bootstrap glyphicon
- [GridView](https://github.com/yiisoft/yii2-framework/blob/2.1/grid/GridView.php) : have a default variable class 'table table-striped table-bordered' who only bootstrap needed, not pure html need
- [ActiveForm](https://github.com/yiisoft/yii2-framework/blob/2.1/widgets/ActiveForm.php) : errorCssClass (has-error),  successCssClass(has-success)
- [ActiveField](https://github.com/yiisoft/yii2-framework/blob/2.1/widgets/ActiveField.php) : default variable in style, container, etc like 'form-group, form-control' is write by default.
- Etc

I'm a bootstrap fan may be (truly) helpful for this, but when used on another ui framework it will all be useless

**Comment by samdark** [comment]
This one is already solved.
