### ISSUE TITLE
New Event for content manipulation (doBody)

### ISSUE THREAD

**Issue by loveorigami** [yiisoft/view#44]
Need new event for content. It is be usefull for parsing shortcodes and replacing them on widgets with assets.

![shortcodes](https://user-images.githubusercontent.com/98164/60545603-1f3d3800-9d24-11e9-98de-aa4ad236deb9.jpg)

Example on yii2
https://github.com/loveorigami/yii2-plugins-system/blob/master/src/components/View.php#L17

more info on Russian (https://yiiframework.ru/forum/viewtopic.php?f=9&t=42209&hilit=shortcodes#p208626)

**Comment by terabytesoftw** [comment]
I think I can implement what you think.

**Comment by rob006** [comment]
Shouldn't this be implemented at widget level, so only content that should be parsed will be parsed? Parsing the whole body seems to be less efficient and more error prone.

**Comment by samdark** [comment]
Could be done as begin()/end() widget that would replace content between these calls.

**Comment by rob006** [comment]
> Could be done as begin()/end() widget that would replace content between these calls.

Isn't it already possible using `EVENT_AFTER_RUN`?

**Comment by samdark** [comment]
Yes, it is possible. Content could be modified in there and modifications will apply to overall result.

**Comment by samdark** [comment]
So it seems the issue is solved.
