### ISSUE TITLE
Improve: allow anonymous functions in View::renderDynamic

### ISSUE THREAD

**Issue by Eseperio** [yiisoft/view#5]
https://github.com/yiisoft/yii2/blob/a72b76877356196544484356d02cac9258f6bda1/framework/base/View.php#L358

When using `View::renderDynamic` code must be written in a string. This disables all ide autocompletion and inspectors. It could be good if closures could be used as parameter, in order to keep all code clean and visible.

**Comment by mj4444ru** [comment]
Serialization of 'Closure' is not allowed.
Method renderDynamic should take a class name, method name and a list of scalar parameters?
Without access to the view and the container, I find it obscenely useless.
