### ISSUE TITLE
PhpTemplateRenderer should prefix $template

### ISSUE THREAD

**Issue by rob006** [yiisoft/view#54]
https://github.com/yiisoft/view/blob/6b50511fd6eac86ef3238e66aacbe1ca2cd5ac13/src/View/PhpTemplateRendererInterface.php#L8-L11

`$template` could be overwritten if `$params` contains `template` key.

BTW: why this *class* has `Interface` suffix?

**Comment by samdark** [comment]
Fixed both issues. Thanks for reporting.
