### ISSUE TITLE
This repo currently needs to depend on yii-core

### ISSUE THREAD

**Issue by kids-return** [yiisoft/view#6]
https://github.com/yiisoft/view/blob/5eccf5b1a9f31861630a359191d2496318e3bfad/src/widgets/WidgetEvent.php#L10

**Comment by samdark** [comment]
Yes. That's where we start.

**Comment by samdark** [comment]
Any ideas?

**Comment by schmunk42** [comment]
Related https://github.com/php-fig/fig-standards/blob/master/proposed/event-dispatcher.md - is there a standard or interface for events?

**Comment by samdark** [comment]
It's in Draft stage.

**Comment by samdark** [comment]
We don't have our own yet.

**Comment by kids-return** [comment]
I think we can first consider the personality of this repo for `yii-view`
This will not affect separation, minimize it, and implement yii2.0 related functions.
because：
https://github.com/yiisoft/yii-web/pull/27#issuecomment-440383678
The view layer is currently weakening and replaced by `vue` and so on.

**Comment by kids-return** [comment]
We should now consider separating and ensuring compliance with yii2.0

**Comment by kids-return** [comment]
Here are some pictures of the current state of `yii framework`

google trends
![image](https://user-images.githubusercontent.com/4520936/48832081-52454380-edb3-11e8-914f-e03628617598.png)

index baidu (Chinese domestic search engine, because many people cannot access google)
![image](https://user-images.githubusercontent.com/4520936/48833183-c680e680-edb5-11e8-80e8-91c93bf69750.png)

china TOP 4 city
![image](https://user-images.githubusercontent.com/4520936/48832864-1e6b1d80-edb5-11e8-9a3d-fd2bc5fdc2d8.png)

2015 year Alibaba
![image](https://user-images.githubusercontent.com/4520936/48832954-4eb2bc00-edb5-11e8-8de7-072963d8186d.png)

2015 year Chinese Government TV
![image](https://user-images.githubusercontent.com/4520936/48833063-8cafe000-edb5-11e8-8ed0-632dcc95791a.png)

After 2015, Yii2 bower caused Chinese users to be unable to install
As far as I know, China is now more popular microservices.
Vue + Rest + docker
Large, medium and small companies are developing on this

**Comment by kids-return** [comment]
Of course, these are just hope that yii can develop better.
After yii3.0 is completed, I will try my best to promote it in China.

**Comment by samdark** [comment]
@kids-return please don't post off-topic. There's a forum for discussions about framework stats and everything that's not directly related to the issue in question: https://forum.yiiframework.com/c/yii-3-0
