### ISSUE TITLE
View with separated positions for ajax

### ISSUE THREAD

**Issue by kamarton** [yiisoft/view#63]
### What steps will reproduce the problem?

Currently, `View` uses magical conditions to work correctly with ajax.

https://github.com/yiisoft/view/blob/4e39cf8a18b148a28e1d585fa29e46f6f9464b3d/src/View/WebView.php#L647-L652

The problem with this is that scripts and css are often unnecessarily output when the page already contains it. It also causes errors and it should be explicitly planned that eg.
- javascript variables should not be overwritten
- do not duplicate events, doubling code runs and other issues.

### What is the expected result?

Separate positions that allow you to (and css alternative)
- only dom ready
- loaded only
- ajax loaded only
- or a combination thereof

### What do you get instead?

Currently, javascript should be designed so as not to cause a problem. Duplicate script and CSS files and contents are parsed after each ajax request.

### I suggests

should be constant values ​​per bit.

```php
registerJs('myScript();', POS_READY);  // dom ready
registerJs('myScript();', POS_AJAX);  // after ajax
registerJs('myScript();', POS_READY | POS_AJAX); // dom ready  + afer ajax
registerJs('myScript();', POS_LOAD | POS_AJAX); // loaded  + afer ajax
registerCss('div {...}', POS_HEAD);
registerCss('div {...}', POS_AJAX);
registerCss('div {...}', POS_HEAD | POS_AJAX);
```

| Q                | A
| ---------------- | ---
| Version          | 3.0.x-dev
| PHP version      | -
| Operating system | -

**Comment by samdark** [comment]
Seems that there are too many cases with exceptions and it should be solved on the application level.
