### ISSUE TITLE
Wrong namespaces

### ISSUE THREAD

**Issue by xepozz** [yiisoft/view#69]
1. Sources of package `view` have wrong namespace. [One](https://github.com/yiisoft/view/blob/master/composer.json#L53) [two](https://github.com/yiisoft/view/blob/master/composer.json#L54) [three](https://github.com/yiisoft/view/blob/master/composer.json#L55) 

2. Tests of package `view` have wrong namespace. [One](https://github.com/yiisoft/view/blob/master/composer.json#L60) [two](https://github.com/yiisoft/view/blob/master/composer.json#L61) [three](https://github.com/yiisoft/view/blob/master/composer.json#L62) [four](https://github.com/yiisoft/view/blob/master/composer.json#L63) 

Just missed package prefix 

### What is the expected result?
The package namespace starts with `YIisoft\View\` for sources and `Yiisoft\View\Tests\` for tests
### What do you get instead?
Chaos in namespace

### Additional info

| Q                | A
| ---------------- | ---
| Version          | 3.0
| Depends on  | https://github.com/yiisoft/view/issues/55

**Comment by samdark** [comment]
Yes. That's being fixed right now by @terabytesoftw starting with https://github.com/yiisoft/assets

**Comment by xepozz** [comment]
What about for `Widget`?

**Comment by samdark** [comment]
That would follow as well.

**Comment by samdark** [comment]
https://github.com/yiisoft/view/issues/34

**Comment by samdark** [comment]
This one is done now.
