### ISSUE TITLE
WebView::registerJsVar with expression

### ISSUE THREAD

**Issue by kamarton** [yiisoft/view#76]
### What steps will reproduce the problem?

Like a yii2 [JsExpression](https://www.yiiframework.com/doc/api/2.0/yii-web-jsexpression) allow variable as complex js expression. For example

```php
$webView->registerJsVar('a', new JsExpression('new Date()'));
$webView->registerJsVar('b', [
  'obj' => new JsExpression('new MyClass()')
  'apple' => 'apple-string',
  'element' => new JsExpression('$(".any")'),
]);
```

| Q                | A
| ---------------- | ---
| Version          | 3.0.x-dev
| PHP version      | -
| Operating system | -

**Comment by samdark** [comment]
Doesn't make sense for current code. Easy to achieve via `registerJs()`.
