### ISSUE TITLE
WebView::renderAjax: event require view file, but in case of ajax not available

### ISSUE THREAD

**Issue by kamarton** [yiisoft/view#78]
### What steps will reproduce the problem?

`WebView::renderAjax()`:
https://github.com/yiisoft/view/blob/d0fa21408657493724ccc36395cb5302145a09c4/src/WebView.php#L201-L206

Events:
https://github.com/yiisoft/view/blob/d0fa21408657493724ccc36395cb5302145a09c4/src/WebView.php#L142

https://github.com/yiisoft/view/blob/d0fa21408657493724ccc36395cb5302145a09c4/src/WebView.php#L150

https://github.com/yiisoft/view/blob/d0fa21408657493724ccc36395cb5302145a09c4/src/View.php#L576

https://github.com/yiisoft/view/blob/d0fa21408657493724ccc36395cb5302145a09c4/src/WebView.php#L163

### What is the expected result?

Expected operation is not very clear for my.
- not call event, OR
- event allow null as view file.

### What do you get instead?

```
TypeError: Argument 1 passed to Yiisoft\View\Event\ViewEvent::__construct() must be of the type string, bool given...
```

### Additional info

| Q                | A
| ---------------- | ---
| Version          | 3.0.x-dev
| PHP version      | -
| Operating system | -

**Comment by vjik** [comment]
Seems this fixed by https://github.com/yiisoft/view/pull/139/files
