### ISSUE TITLE
View and WebView: events not present sender

### ISSUE THREAD

**Issue by kamarton** [yiisoft/view#79]
### What steps will reproduce the problem?

In Yii2, the event sender was available, which is very useful if event-based processes want to modify the sender, e.g. Add CSS, JS.

https://www.yiiframework.com/doc/api/2.0/yii-base-event#$sender-detail

> The $sender property describes who raises the event.

### What is the expected result?

The sender object is accessible.

### What do you get instead?

Do I need to create a separate dispatcher? This makes the process complicated if I have to use it multiple times and the process is only partially different, e.g. create email template and create web response in one request.

| Q                | A
| ---------------- | ---
| Version          | 3.0.x-dev
| PHP version      | -
| Operating system | -

**Comment by samdark** [comment]
You can add reference to the view to the event object.

**Comment by kamarton** [comment]
> Which events do you mean?

```
\Yiisoft\View\Event\BodyEnd
\Yiisoft\View\Event\PageEnd
```

I can use multiple WebViews within the process, e.g. HTTP response body, HTML export. For example, if I want to place a tracking javascript at the bottom of the BODY on an event trigger.

```php
function(object $event)
{
  $view = $event->sender;
  /* @var $view WebView */
  $view->registerJs('...');
}
```

**Comment by kamarton** [comment]
I feel that this is a global problem with Yii3, because `$sender` is not available for other non-view events. In Yii2, this was a very useful manipulation method, where it was possible to handling events at bootstrap level and influence further operation.

**Comment by samdark** [comment]
Makes sense to add reference to View to \Yiisoft\View\Event\BodyEnd and Yiisoft\View\Event\PageEnd.
