### ISSUE TITLE
Ensure view is able to work with event loop

### ISSUE THREAD

**Issue by samdark** [yiisoft/view#90]
For event loop, such as RoadRunner, the service should be either immutable or should have a method to reset the state.

**Comment by yiiliveext** [comment]
This isn't an appropriate solution. WebView is a singleton service, so it can be accessed from anywhere.

**Comment by samdark** [comment]
@yiiliveext yes, indeed. You're correct.

**Comment by mj4444ru** [comment]
> This isn't an appropriate solution. WebView is a singleton service, so it can be accessed from anywhere.

It looks strange. The functionality of the WebView should only be used inside the layout template. External rendering components don't need to know about the existence of the WebView.

**Comment by yiiliveext** [comment]
> It looks strange. The functionality of the WebView should only be used inside the layout template. External rendering components don't need to know about the existence of the WebView.

Example:

//config/events-web.php

return [
    \Yiisoft\View\Event\BeforeRender::class => [
        fn (object $e, WebView $view) => $view->registerMetaTag(....),
    ]
]

**Comment by mj4444ru** [comment]
> Example:
> 
> ```
> //config/events-web.php
> 
> return [
>     BeforeRequest::class => [
>         fn (object $e, WebView $view) => $view->registerMetaTag(....),
>     ]
> ]
> ```

This is an example of how you definitely shouldn't.
There are corresponding interfaces to implement such things, for example MetaTagsInjectionInterface.

**Comment by yiiliveext** [comment]
> There are corresponding interfaces to implement such things, for example MetaTagsInjectionInterface.

This is `yii-view` package. I don't have to use this package together with `WebView`.

**Comment by mj4444ru** [comment]
If you don't want to use Yiisoft\Yii\View\ViewRenderer, you can easily do the following:
```php
//config/events-web.php

return [
    BeforeRequest::class => [
        fn (object $e, WebView $view) => $view->clear(),
    ]
]
```

**Comment by yiiliveext** [comment]
> If you don't want to use Yiisoft\Yii\View\ViewRenderer, you can easily do the following:
> 
> ```
> //config/events-web.php
> 
> return [
>     BeforeRequest::class => [
>         fn (object $e, WebView $view) => $view->clear(),
>     ]
> ]
> ```

`Clear` method is not enough. WebView inherits many properties from `View`.

**Comment by mj4444ru** [comment]
> `Clear` method is not enough. WebView inherits many properties from `View`.

Then you can use this solution for applications like RoadRunner:
https://github.com/yiisoft/di/pull/153
